ktor:
  application:
    modules:
      - ApplicationKt.module
  deployment:
    port: ${PORT:8000}
  security:
    supabaseUrl: $SUPABASE_URL
    supabaseKey: $SUPABASE_KEY
    googleClientId: $GOOGLE_CLIENT_ID
    revision: $REVISION
